### ISSUE TITLE
Where's Androidmanifest.xml ?

### ISSUE THREAD

**Issue by ghost** [IvonLiu/moscrop-secondary-app#1]
Anyone Active?

**Comment by AllanWang** [comment]
This repo hasn't been maintained in a while, but [here](https://github.com/moscrop-secondary-school/moscrop-secondary-app/blob/master/moscropApp/src/main/AndroidManifest.xml) is the manifest

**Comment by KadwaP** [comment]
Im trying to create a app for the SD36 district and i found this is a base. i'll try this right now.
